//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvSeriesCalendar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TvSeriesCalendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap defaultSeries {
            get {
                object obj = ResourceManager.GetObject("defaultSeries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading_blackBG {
            get {
                object obj = ResourceManager.GetObject("loading_blackBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading_whiteBG {
            get {
                object obj = ResourceManager.GetObject("loading_whiteBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TvSeriesCalendar
        ///
        ///THIRD-PARTY SOFTWARE NOTICES AND INFORMATION
        ///Do Not Translate or Localize
        ///
        ///1.	LordMike/TMDbLib version 1.6.0 (https://github.com/LordMike/TMDbLib)
        ///2.	JamesNK/Newtonsoft.Json version 12.0.3 (https://github.com/JamesNK/Newtonsoft.Json)
        ///3.	TheMovieDatabase API (https://www.themoviedb.org/)
        ///4.  wixtoolset/wix3 (https://github.com/wixtoolset/wix3)
        ///5.  diub/TaskScheduler Source Code (https://dotnet-snippets.de/snippet/windows-aufgabenplaner-taskscheduler-benutzen/15191)
        ///
        ///
        ///LordMike/TM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThirdPartyNotices {
            get {
                return ResourceManager.GetString("ThirdPartyNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TMDbLogo {
            get {
                object obj = ResourceManager.GetObject("TMDbLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TvSeriesCalendar {
            get {
                object obj = ResourceManager.GetObject("TvSeriesCalendar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set WshShell = CreateObject(&quot;WScript.Shell&quot;)
        ///Dim objWMIService, colProcessList
        ///Set objWMIService = GetObject(&quot;winmgmts:&quot; &amp; &quot;{impersonationLevel=impersonate}!\\&quot; &amp; &quot;.&quot; &amp; &quot;\root\cimv2&quot;)
        ///if WScript.Arguments.Count &lt;&gt; 2 then
        ///    WScript.Echo &quot;Something Went Wrong&quot;
        ///	WScript.Quit 1
        ///end if
        ///Set colProcessList = objWMIService.ExecQuery(&quot;SELECT * FROM Win32_Process WHERE ProcessId = &apos;&quot; &amp; WScript.Arguments(0) &amp; &quot;&apos;&quot;)
        ///Do While colProcessList.Count = 1
        ///	WScript.Sleep 100
        ///	Set colProcessList = objWMIService.Exec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whiteMinus {
            get {
                object obj = ResourceManager.GetObject("whiteMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whitePlus {
            get {
                object obj = ResourceManager.GetObject("whitePlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whiteX {
            get {
                object obj = ResourceManager.GetObject("whiteX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
